<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Project extends Model
{
    use HasFactory;

    const TYPE_FIXED = 'fixed';
    const TYPE_HOURLY = 'hourly';

    protected $fillable = [
        'title', 'category_id', 'user_id', 'description', 'min_budget','max_budget',
        'status', 'type','location'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function files()
    {
        return $this->morphMany(Image::class, 'imageable')->where('feature', 1);
    }

    public function tags()
    {
        return $this->belongsToMany(
            Tag::class,
            'project_tag',
            'project_id',
            'tag_id',
            'id',
            'id'
        );
    }

    public static function types()
    {
        return [
            self::TYPE_FIXED => 'Fixed',
            self::TYPE_HOURLY => 'Hourly',
        ];
    }

    public function syncTags(array $tags)
    {
        $tags_id = [];
        foreach ($tags as $tag_name) {
            $tag = Tag::firstOrCreate([
                'slug' => Str::slug($tag_name),
            ], [
                'name' => trim($tag_name),
            ]);
            $tags_id[] = $tag->id;
        }
        $this->tags()->sync($tags_id);
    }

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::creating(function ($value) {
            $slug = Str::slug(request()->title);
            $count = Project::where('slug', 'like', $slug . '%')->count();
            if ($count) {
                $slug = $slug . '-' . $count;
            }

            $value->slug = $slug;
        });
    }

    public function proposals()
    {
        return $this->hasMany(Proposal::class);
    }

    public function proposedFreelancers()
    {
        return $this->belongsToMany(
            User::class,
            Proposal::class,
            'project_id',
            'freelancer_id',
        )->withPivot([
            'description', 'cost', 'duration', 'duration_unit', 'status',
        ]);
    }

    public function contracts()
    {
        return $this->hasMany(Contract::class);
    }
    public function contractedFreelancers()
    {
        return $this->belongsToMany(
            User::class,
            'contracts',
            'project_id',
            'freelancer_id',
        )->withPivot([
            'proposal_id', 'cost',
            'type', 'start_on', 'end_on', 'completed_on', 'hours', 'status'
        ]);
    }

}
